version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - gocritic
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - depguard
    - revive
    - wsl
    - mnd
    - exhaustruct
    - exhaustive
